name: test

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight

  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop

env:
  IMAGE_NAME: 'hadenlabs/terraform-aws-openvpn'

jobs:
  test:
    name: test
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: check out a copy of the repo
        uses: actions/checkout@v2
      - name: build the docker image
        run: |
          docker build . --tag ${{ env.IMAGE_NAME }}:latest
      - name: install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: test
        run: go test ./...
